### ISSUE TITLE
UE4 2.27 crash when openning sub-section of the map

### ISSUE THREAD

**Issue by onlyinheaven** [Activision/caldera#5]
Hi，
    When using the USD Level plugin in UE4 to open the sub-map map_source/prefabs/br/wz_vg/mp_wz_island/commercial/hotel_01.usd, UE4 crashes with the following error message:
    Assertion failed: !bOnlyOneRootAllowed || (((BoneIndex == 0) && (BoneInfo.ParentIndex == INDEX_NONE)) || ((BoneIndex > 0) && RawRefBoneInfo.IsValidIndex(BoneInfo.ParentIndex) && (BoneInfo.ParentIndex < BoneIndex))) [File:D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Public\ReferenceSkeleton.h] [Line: 203].
    The crash log is attached. I wonder is it possible to open the scene by unreal engine? [
[calderatest.log](https://github.com/user-attachments/files/16466369/calderatest.log)
](url)
Thanks

**Comment by koen-v** [comment]
Hello, 

I am not sure about UE4, but I have successfully loaded the hotel into the latest UE5.

Cheers,
Koen

**Comment by onlyinheaven** [comment]
> Hello,
> 
> I am not sure about UE4, but I have successfully loaded the hotel into the latest UE5.
> 
> Cheers, Koen

Thanks, I have successfully loaded the USD model using UE5, but I noticed that there are no texture maps on the model. Is it because I didn't load it completely, or do the currently available models not include texture maps? If it's the latter, do you have plans to release the texture maps？

**Comment by koen-v** [comment]
There are no textures included in this release and at the moment there are no plans to include those. A little blurb from the readme:

`We have also chosen not to include textures and materials in this release. This would add complexity and size to an already heavy scene. Our focus is on the many relationships between spatial elements to be discovered in this set more than aiming for an accurate visual representation.`

Cheers,
Koen
